name: Build and Release

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build-and-release:
    runs-on: docker.m.daocloud.io/library/ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: docker.m.daocloud.io/library/actions/checkout@v4
        
      - name: Setup Node.js
        uses: docker.m.daocloud.io/library/actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: docker.m.daocloud.io/library/pnpm/action-setup@v4
        with:
          version: latest
          
      - name: Set pnpm registry
        run: pnpm config set registry https://registry.npmmirror.com
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build project
        run: pnpm build
        
      - name: Package project
        run: pnpm package
        
      - name: Create Release
        id: create_release
        uses: docker.m.daocloud.io/library/actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: docker.m.daocloud.io/library/actions/upload-release-asset@v1  # 使用国内镜像源
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/chrome-mv3-prod.zip
          asset_name: chrome-mv3-prod.zip
          asset_content_type: application/zip