name: release

on:
  push:
    tags:
      - v* 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        run: npm run package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # 升级到 v4
        with:
          name: chrome-mv3-prod
          path: build/chrome-mv3-prod.zip

  upload-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4  # 升级到 v4
        with:
          name: chrome-mv3-prod
          path: build/  # 保持路径配置

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/chrome-mv3-prod.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false